//in the name of ALLAH
//YA MAHDI

#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <QString>

// جداکننده‌ی فیلدها در پیام‌های پروتکل: COMMAND||field1||field2||...
const QString PROTOCOL_SEPARATOR = "||";

enum class Command {
    UNKNOWN,

    SUCCESS,
    FAIL,

    LOGIN,
    SIGNUP_PUBLISHER,
    SIGNUP_NORMALUSER,
    FORGOT_PASS_CHECK,
    FORGOT_PASS_UPDATE,
    LOGOUT,
    SET_FAVORITE_GENRES,

    GET_PUBLISHER_BOOKS,
    PUBLISHER_BOOKS_RESULT,
    GET_BOOK_DETAILS,
    BOOK_DETAILS_RESULT,
    ADD_BOOK_METADATA,
    ADD_BOOK_RESULT,
    UPLOAD_PDF_START,
    UPLOAD_PDF_CHUNK,
    UPLOAD_PDF_END,
    UPLOAD_PDF_RESULT,
    EDIT_BOOK,
    EDIT_BOOK_RESULT,
    TOGGLE_BOOK_STATUS,
    TOGGLE_STATUS_RESULT,
    DELETE_BOOK,
    SEARCH_STOREPAGE,
    SEARCH_RESULT,
    GET_BOOK_SUMMARY,
    BOOK_SUMMARY,

    BUY,
    GET_CART_ITEMS,
    CART_RESULT,
    GET_CART_BOOK_SUMMARY,
    CART_BOOK_SUMMARY,
    ADD_CART,
    REMOVE_CART,
    CHECKOUT_CART,
    CHECKOUT_RESULT,

    GET_MY_BOOKS,
    MY_BOOKS_RESULT,
    GET_SAVED_BOOKS,
    SAVED_BOOKS_RESULT,
    GET_SHELVES,
    SHELVES_RESULT,
    GET_SHELF_BOOKS,
    SHELF_BOOKS_RESULT,
    GET_MY_BOOK_INFO,
    MY_BOOK_INFO_RESULT,
    GET_SAVED_BOOK_INFO,
    SAVED_BOOK_INFO_RESULT,
    GET_SHELF_BOOK_INFO,
    SHELF_BOOK_INFO_RESULT,
    ADD_SHELF,
    ADD_SHELF_RESULT,
    EDIT_SHELF,
    EDIT_SHELF_RESULT,
    DELETE_SHELF,
    DELETE_SHELF_RESULT,
    REMOVE_FROM_SAVED,
    REMOVE_SAVED_RESULT,
    REMOVE_FROM_SHELF,
    REMOVE_FROM_SHELF_RESULT,
    ASSIGN_TO_SHELF,
    ASSIGN_SHELF_RESULT,
    DOWNLOAD_BOOK,
    FILE_START,
    FILE_CHUNK,
    FILE_END,
    UPDATE_LAST_PAGE,
    SAVE_BOOK,
    GET_COMMENTS_LIST,
    COMMENTS_LIST,
    GET_COMMENT_DETAILS,
    COMMENT_DETAILS,
    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
    COMMENT_UPDATED,

    GET_DATA_USERPROFILE,
    USER_PROFILE_INFO,
    GET_HISTORY_IDS,
    HISTORY_IDS,
    GET_HISTORY_BOOK,
    HISTORY_BOOK_INFO,
    UPDATE_BALANCE,
    UPDATE_PROFILE,
    UPDATE_PROFILE_RESULT,

    GET_PUB_GENERAL_STATS,
    PUB_GENERAL_RESULT,
    GET_PUB_TOP_BOOKS_IDS,
    PUB_TOP_IDS_RESULT,
    GET_PUB_BOOK_INFO_TOP,
    PUB_BOOK_INFO_TOP_RESULT,
    GET_PUB_LOWEST_BOOKS_IDS,
    PUB_LOWEST_IDS_RESULT,
    GET_PUB_BOOK_INFO_LOWEST,
    PUB_BOOK_INFO_LOWEST_RESULT,
    GET_PUB_SALES_CHART,
    PUB_SALES_CHART_RESULT,
    GET_PUB_SCORE_CHART,
    PUB_SCORE_CHART_RESULT,

    SEARCH_USERS,
    USERS_LIST_RESULT,
    GET_USER_INFO,
    USER_INFO_RESULT,
    DELETE_USER,
    DELETE_USER_RESULT,
    BLOCK_USER,
    BLOCK_USER_RESULT,
    UNBLOCK_USER,
    UNBLOCK_USER_RESULT
};

QString commandToString(Command command);

Command stringToCommand(const QString &text);

#endif
